### ISSUE TITLE
wrk2.yaml.tmpl problem

### ISSUE THREAD

**Issue by kason-huang** [kinvolk/service-mesh-benchmark#10]
I occur a problem. When I run the benchmark.sh file, I get the following error message.
> Error from server (BadRequest): error when creating "./benchmark-load-generator.injected.yaml": Job in version "v1" cannot be handled as a Job: v1.Job.Spec: v1.JobSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.VolumeMounts: []v1.VolumeMount: Name: Image: Args: []string: ReadString: expects " or n, but found 2, error found in #10 byte of ...|ua","-d",2,"-R","100|..., bigger context ...|080","--","-s","/etc/wrk2/multi-server.lua","-d",2,"-R","100","-c","8","-t","8","--latency","--timeo|...

I found out the problem is because of wrk2.yaml.tmpl, the definition of "benchmark-load-generator". 
>   args:
        - -i
        - "1"
        - -s
        - "60"
        - "http://web-svc-1.emojivoto.svc.cluster.local:8080"
        - --
            # wrk args
        - -s
        - /etc/wrk2/multi-server.lua
        - -d
        - ${DURATION}

after render, the ${DURATION} will be replace by a value, for example 6.  This is why the problem occur. See also [job defintion](https://stackoverflow.com/questions/43549192/failure-to-create-a-job-in-kubernetes-due-to-error). When I change the ${DURATION} to "${DURATION}", it work. But I do not know whether the change will effect the result of the experiment?
The problem is because of the k8s version? I use the 1.10.6.
Thanks.

**Comment by kason-huang** [comment]
By the way , how many nodes do I need for the experiment?

**Comment by t-lo** [comment]
> after render, the ${DURATION} will be replace by a value, for example 6. This is why the problem occur. See also job defintion. When I change the ${DURATION} to "${DURATION}", it work. But I do not know whether the change will effect the result of the experiment?

Good catch! The reason this breaks for you is probably because you specified the duration without a unit (i.e. 2 instead of 2s, 2m, 2h, ...). Kubernetes then believes this to be a number, but command line arguments need to be a string. To work around this, you may either use units, or go with your suggestion of using double quotes around the ${DURATION} variable (no unit will use seconds implicitly and won't have a bad effect on the outcome).

> By the way , how many nodes do I need for the experiment?

The automation will reserve one node in the cluster for benchmark load generation, and leave the remainder to the application (emojivoto). This is done by tainting a random node with a NoSchedule tag that the benchmark deployment has a toleration for, see https://github.com/kinvolk/service-mesh-benchmark/blob/e5f4244ef3341fadda8b8deb85cc972dea18c758/scripts/common.sh#L79 .

So technically, 2 worker nodes will suffice to use the automation to run benchmarks. However, given emojivoto's distributed micro-architecture as well as the benchmark automation feature of deploying an arbitrary number of emojivoto instances, we recommend to use a 5-node cluster, leaving 4 nodes to the (multiple) application (instances).

**Comment by kason-huang** [comment]
Thanks a lot. But I only have two nodes, I would use  "nr_apps=2" "duration=4" “rate=100” "threads=8" to finish the experiment. Is this configuration appropriate?

**Comment by t-lo** [comment]
I'd start with a longer duration - 60s is not a bad value. 4(s) will give you noticeable jitter over multiple runs (even wkr2's warm-up phase is 10s at least).

The rate seems a little low, but then this strongly depends on the computing power of your nodes. You can always increase the rate in successive runs to gauge the limits of your set-up.

The number of threads strongly depend on the machine you'll be running the benchmark pod on. As a rule of thumb, if you don't saturate all cores on that node, keep increasing the thread count. Also please notice that our modification to wrk2, which enables support of benchmarking multiple endpoints instead of just one, requires the number of connections (-c) to be equal to the number of threads.
