### ISSUE TITLE
Reproduce the benchmark result

### ISSUE THREAD

**Issue by kason-huang** [kinvolk/service-mesh-benchmark#9]
Can I use the code to reproduce the benchmark result in my own k8s cluster which is deployed in my local machine?

**Comment by t-lo** [comment]
The project as-is ships [Lokomotive Kubernetes](https://github.com/kinvolk/lokomotive-kubernetes) and sets up a cluster on the [Packet](https://www.packet.com/) IaaS provider. However, it should be possible to just use parts of the automation to set up istio or linkerd on an existing cluster.

Please have a look at `scripts/istio/setup-cluster.sh` and `scripts/linkerd/setup-cluster.sh`, respectively,   make sure `KUBECONFIG` points to your `kubeconfig` (instead of trying to guess via terraform as it does currently), and ensure `ask_create_cluster` is never called.

On a closing note, this code is from May 2019, and was tested with `istio-1.1.6` and `linkerd2-edge-19.5.2`. Both linkerd and istio have seen significant improvements 'til then, but later versions have not been tested with the code. If you plan to add support for newer releases please do consider to file a PR with us :)

**Comment by kason-huang** [comment]
OK, thanks

**Comment by t-lo** [comment]
I'll close this issue as I believe the request was satisfied. Please do not hesitate to re-open if necessary.
